/* قاعدة المعرفة الطبية — محتوى عربي/إنجليزي مزدوج */
const DB = {

/* ===== الدليل الغذائي (14 حالة) ===== */
FOOD: [
 {k:"constipation", ar:"الإمساك", en:"Constipation",
  ok_ar:["الشوفان والحبوب الكاملة","التفاح والكمثرى والتين المجفف","الخضروات الورقية","الماء بوفرة (8–10 أكواب)","البقوليات بإضافة تدريجية"],
  no_ar:["الخبز الأبيض والحلويات","الإفراط في الشاي والقهوة","الأطعمة المكررة المصنعة","الإفراط في الحليب الدسم"],
  note_ar:"زد الألياف تدريجيًا مع كثرة السوائل. استمرار الإمساك أكثر من أسبوعين أو دم في البراز = مراجعة طبيب.",
  ok_en:["Oats and whole grains","Apples, pears, dried figs","Leafy vegetables","Plenty of water (8–10 cups)","Legumes added gradually"],
  no_en:["White bread and sweets","Excess tea and coffee","Refined processed foods","Excess full-fat milk"],
  note_en:"Increase fiber gradually with fluids. Constipation over 2 weeks or blood in stool = see a doctor."},
 {k:"diabetes", ar:"السكري (النوع الثاني)", en:"Type 2 diabetes",
  ok_ar:["الحبوب الكاملة (شوفان، برغل)","البقوليات","الخضروات غير النشوية","السمك والدجاج بدون جلد","المكسرات النيئة باعتدال"],
  no_ar:["السكريات المضافة والحلويات","العصائر والمشروبات المحلاة","الخبز والأرز الأبيض","الفواكه المجففة بكثرة","المقليات"],
  note_ar:"لا تعدّل أي دواء بنفسك — أي تغيير غذائي كبير ناقشه مع طبيبك لتجنب هبوط السكر.",
  ok_en:["Whole grains (oats, bulgur)","Legumes","Non-starchy vegetables","Fish and skinless chicken","Raw nuts in moderation"],
  no_en:["Added sugars and sweets","Juices and sugary drinks","White bread and rice","Dried fruits in excess","Fried foods"],
  note_en:"Never adjust medication on your own — discuss major diet changes with your doctor to avoid hypoglycemia."},
 {k:"hemorrhoids", ar:"البواسير", en:"Hemorrhoids",
  ok_ar:["الألياف (30غ يوميًا)","التوت والحمضيات","السوائل بوفرة","الزبادي"],
  no_ar:["الفلفل الحار جدًا","الكحول","الإفراط في الكافيين","الأطعمة المسببة للإمساك"],
  note_ar:"نزيف شرجي متكرر أو كبير ليس بالضرورة بواسير — راجع طبيبًا لاستبعاد أسباب أخرى.",
  ok_en:["Fiber (30g/day)","Berries and citrus","Plenty of fluids","Yogurt"],
  no_en:["Very spicy peppers","Alcohol","Excess caffeine","Constipation-causing foods"],
  note_en:"Recurrent or heavy rectal bleeding is not necessarily hemorrhoids — see a doctor to rule out other causes."},
 {k:"hypertension", ar:"ضغط الدم المرتفع", en:"High blood pressure",
  ok_ar:["الخضروات الورقية","الشوفان والحبوب الكاملة","البنجر","الأسماك","الزبادي قليل الدسم","الثوم"],
  no_ar:["الملح والمخللات","اللحوم المصنعة","المشروبات الغازية","الكحول"],
  note_ar:"تنبيه تعارض: الجريب فروت يتعارض مع بعض أدوية الضغط — استشر طبيبك قبل تناوله.",
  ok_en:["Leafy vegetables","Oats and whole grains","Beetroot","Fish","Low-fat yogurt","Garlic"],
  no_en:["Salt and pickles","Processed meats","Sodas","Alcohol"],
  note_en:"Interaction alert: grapefruit interacts with some blood-pressure medicines — ask your doctor first."},
 {k:"gout", ar:"النقرس", en:"Gout",
  ok_ar:["الماء بوفرة","الحبوب الكاملة","الكرز والفواكه","الخضروات","الألبان قليلة الدسم"],
  no_ar:["اللحوم الحمراء والكبد والكلى","المحار والروبيان","السردين والأنشوجة","الكحول خاصة البيرة","المشروبات المحلاة بالفركتوز"],
  note_ar:"نوبة مفصل حاد مع احمرار وسخونة = مراجعة عاجلة.",
  ok_en:["Plenty of water","Whole grains","Cherries and fruits","Vegetables","Low-fat dairy"],
  no_en:["Red meat, liver, kidneys","Shellfish and shrimp","Sardines and anchovies","Alcohol especially beer","Fructose-sweetened drinks"],
  note_en:"An acute hot, red joint attack = urgent review."},
 {k:"reflux", ar:"الحموضة والارتجاع", en:"Acid reflux / GERD",
  ok_ar:["وجبات صغيرة متكررة","الشوفان والخبز المحمص","الخضروات غير الحمضية","الزنجبيل","الموز الناضج"],
  no_ar:["القهوة والكافيين","المقليات والدهون الثقيلة","الشوكولاتة","الطماطم والحمضيات","الوجبات الكبيرة قبل النوم"],
  note_ar:"ألم صدري مع إجهاد أو ضيق نفس ليس حموضة — اطلب رعاية طارئة فورًا.",
  ok_en:["Small frequent meals","Oats and toast","Non-acidic vegetables","Ginger","Ripe banana"],
  no_en:["Coffee and caffeine","Fried and fatty foods","Chocolate","Tomatoes and citrus","Large meals before bed"],
  note_en:"Chest pain with exertion or breathlessness is not reflux — seek emergency care immediately."},
 {k:"anemia", ar:"فقر الدم (نقص الحديد)", en:"Iron-deficiency anemia",
  ok_ar:["اللحم الأحمر","العدس والحمص","السبانخ والبقوليات","فيتامين C مع الوجبات"],
  no_ar:["الشاي والقهوة مع الوجبات","الحليب مع وجبات الحديد","الإفراط في الأغذية المصنعة"],
  note_ar:"فيتامين C يرفع امتصاص الحديد والشاي يثبطه. يجب تحديد سبب فقر الدم طبيًا.",
  ok_en:["Red meat","Lentils and chickpeas","Spinach and legumes","Vitamin C with meals"],
  no_en:["Tea and coffee with meals","Milk with iron-rich meals","Excess processed foods"],
  note_en:"Vitamin C boosts iron absorption; tea blocks it. The cause of anemia must be found medically."},
 {k:"stones", ar:"حصوات الكلى", en:"Kidney stones",
  ok_ar:["الماء 2.5–3 لتر يوميًا","الليمون","البطيخ","الكالسيوم الغذائي الطبيعي"],
  no_ar:["الملح الزائد","اللحوم بكثرة","المكملات العشوائية","المشروبات الغازية"],
  note_ar:"حمى مع ألم خاصرة = التهاب حوض الكلى المشتبه — مراجعة عاجلة.",
  ok_en:["Water 2.5–3 L/day","Lemon","Watermelon","Natural dietary calcium"],
  no_en:["Excess salt","Excess meat","Random supplements","Sodas"],
  note_en:"Fever with flank pain = suspected kidney infection — urgent review."},
 {k:"diarrhea", ar:"الإسهال", en:"Diarrhea",
  ok_ar:["محلول الأملاح والسوائل","الأرز الأبيض","الخبز المحمص","الموز والجوافة المطهوة"],
  no_ar:["الألبان مؤقتًا","الأطعمة الدهنية","الأطعمة الحارة","الكافيين والعصائر المحلاة"],
  note_ar:"علامات خطر: جفاف، دم في البراز، حمى، أو استمرار أكثر من 3 أيام = مراجعة طبية.",
  ok_en:["Oral rehydration and fluids","White rice","Toast","Banana and cooked guava"],
  no_en:["Dairy (temporarily)","Fatty foods","Spicy foods","Caffeine and sweet juices"],
  note_en:"Red flags: dehydration, blood in stool, fever, or lasting over 3 days = medical review."},
 {k:"ibs", ar:"القولون العصبي", en:"Irritable bowel syndrome",
  ok_ar:["وجبات صغيرة منتظمة","الشوفان والأرز","الزبادي","أطعمة FODMAP منخفضة حسب التحمل"],
  no_ar:["الإفراط في الكافيين","المقليات","المشروبات الغازية","الأطعمة الحارة"],
  note_ar:"تحذير أحمر: دم في البراز، فقدان وزن غير مفسّر، فقر دم، أو بدء الأعراض بعد سن 50 = فحص ضروري.",
  ok_en:["Small regular meals","Oats and rice","Yogurt","Low-FODMAP foods per tolerance"],
  no_en:["Excess caffeine","Fried foods","Carbonated drinks","Spicy foods"],
  note_en:"Red flags: blood in stool, unexplained weight loss, anemia, or new symptoms after 50 = needs work-up."},
 {k:"obesity", ar:"السمنة", en:"Obesity",
  ok_ar:["بروتين خفيف (دجاج، سمك، بيض)","الخضروات","الحبوب الكاملة","الماء قبل الوجبات"],
  no_ar:["المشروبات المحلاة","الوجبات السريعة","السكريات المخفية","الأكل الليلي بكثرة"],
  note_ar:"ممنوع اقتراح حميات قاسية أو صيام متقطع لمرضى السكري أو الحوامل دون إشراف.",
  ok_en:["Lean protein (chicken, fish, eggs)","Vegetables","Whole grains","Water before meals"],
  no_en:["Sugary drinks","Fast food","Hidden sugars","Heavy night eating"],
  note_en:"No crash diets or fasting for diabetics or pregnant women without supervision."},
 {k:"osteoporosis", ar:"هشاشة العظام", en:"Osteoporosis",
  ok_ar:["منتجات الألبان","السمك بالعظم","السمسم","الخضروات الورقية","التعرض للشمس"],
  no_ar:["الإفراط في الكافيين","المشروبات الغازية بكثرة","الملح الزائد","التدخين"],
  note_ar:"ألم ظهر مفاجئ مع نقص الطول = كسور ضغطية محتملة.",
  ok_en:["Dairy","Fish with bones","Sesame","Leafy vegetables","Sunlight exposure"],
  no_en:["Excess caffeine","Excess sodas","Excess salt","Smoking"],
  note_en:"Sudden back pain with height loss = possible compression fracture."},
 {k:"hypothyroid", ar:"خمول الغدة الدرقية", en:"Hypothyroidism",
  ok_ar:["اليود المعتدل (أسماك، ألبان)","السيلينيوم (مكسرات، بيض)","الحبوب الكاملة"],
  no_ar:["الصويا والملفوف والقرنبيط بكثرة عند نقص اليود","الوجبات الثقيلة"],
  note_ar:"الشاي والقهوة والألياف تثبط امتصاص ليفوثيروكسين — افصل 4 ساعات.",
  ok_en:["Moderate iodine (fish, dairy)","Selenium (nuts, eggs)","Whole grains"],
  no_en:["Excess soy, cabbage, cauliflower with iodine deficiency","Heavy meals"],
  note_en:"Tea, coffee and fiber block levothyroxine absorption — separate by 4 hours."},
 {k:"ckd", ar:"أمراض الكلى المزمنة", en:"Chronic kidney disease",
  ok_ar:["بروتين معتدل حسب الدرجة","خضروات منخفضة البوتاسيوم","توابل بدل الملح"],
  no_ar:["الملح","البوتاسيوم العالي (موز، بطاطس، أفوكادو) بكثرة","المكملات العشوائية","الإفراط في البروتين"],
  note_ar:"هذه الحالة عكس النصائح العامة: «الأطعمة الصحية» كالبوتاسيوم قد تكون خطيرة — التزم بخطة طبيبك.",
  ok_en:["Moderate protein per stage","Low-potassium vegetables","Herbs instead of salt"],
  no_en:["Salt","High-potassium foods (banana, potato, avocado) in excess","Random supplements","Excess protein"],
  note_en:"Opposite of general advice: 'healthy' potassium-rich foods can be dangerous here — follow your doctor's plan."}
],

/* ===== الأدوية (بطاقات تثقيفية) ===== */
MEDS: [
 {name:"Paracetamol (باراسيتامول)", p_ar:"خافض للحرارة ومسكن خفيف إلى متوسط", b_ar:["ألم خفيف","حمى","آمن نسبيًا على المعدة"],
  s_ar:["نادر عند الجرعة الصحيحة"], w_ar:["أقصى 4غ يوميًا للبالغين","تجنب مع أدوية البرد المركبة (تكرار المادة)","حذر شديد مع أمراض الكبد"],
  i_ar:"يتعارض مع الكحول (سمية كبدية).",
  p_en:"Fever reducer and mild-to-moderate pain reliever", b_en:["Mild pain","Fever","Relatively stomach-safe"],
  s_en:["Rare at correct doses"], w_en:["Max 4g/day for adults","Avoid combining with multi-symptom cold meds","Caution with liver disease"],
  i_en:"Alcohol increases liver toxicity."},
 {name:"Ibuprofen (إيبوبروفين)", p_ar:"مضاد التهاب لاستطباعي (NSAID)", b_ar:["الألم الالتهابي","المغص","الصداع النصفي"],
  s_ar:["تهيج معدة","احتباس سوائل","دوخة"], w_ar:["يؤخذ مع الطعام","تجنب مع قرحة المعدة أو أمراض الكلى","حذر مع ضغط الدم وأدوية التخثر"],
  i_ar:"يتعارض مع مميعات الدم والكورتيزون وأدوية الضغط.",
  p_en:"NSAID anti-inflammatory", b_en:["Inflammatory pain","Cramps","Migraine"],
  s_en:["Stomach irritation","Fluid retention","Dizziness"], w_en:["Take with food","Avoid with gastric ulcer or kidney disease","Caution with hypertension and anticoagulants"],
  i_en:"Interacts with blood thinners, steroids and BP meds."},
 {name:"Amoxicillin (أموكسيسيلين)", p_ar:"مضاد حيوي من البنسلين", b_ar:["التهابات بكتيرية حساسة"],
  s_ar:["إسهال","طفح","غثيان"], w_ar:["إكمل المدة حتى لو تحسّنت","أخبر طبيبك بأي حساسية سابقة للبنسلين"],
  i_ar:"يقلل فعالية حبوب منع الحمل أثناء الدورة وبعدها بأيام.",
  p_en:"Penicillin antibiotic", b_en:["Susceptible bacterial infections"],
  s_en:["Diarrhea","Rash","Nausea"], w_en:["Complete the full course","Report any previous penicillin allergy"],
  i_en:"May reduce oral contraceptive efficacy."},
 {name:"Omeprazole (أوميبرازول)", p_ar:"مثبط مضخة البروتون — يقلل حمض المعدة", b_ar:["الارتجاع","القرحة","الحموضة المزمنة"],
  s_ar:["صداع","غازات"], w_ar:["جرعات طويلة قد تخفض المغنيسيوم وB12","استشر طبيبك قبل الاستخدام الطويل"],
  i_ar:"يؤثر على امتصاص الأدوية التي تحتاج حمضًا.",
  p_en:"Proton pump inhibitor — reduces stomach acid", b_en:["Reflux","Ulcer","Chronic heartburn"],
  s_en:["Headache","Gas"], w_en:["Long use may lower magnesium and B12","Consult before long-term use"],
  i_en:"Affects absorption of acid-dependent drugs."},
 {name:"Metformin (ميتفورمين)", p_ar:"خافض لسكر الدم للنوع الثاني", b_ar:["يحسن الحساسية للأنسولين","لا يسبب هبوطًا شديدًا وحده"],
  s_ar:["غثيان","إسهال (يتحسن عادة)"], w_ar:["يوقف مؤقتًا قبل العمليات وبعد اختبارات الصبغة","حذر مع أمراض الكلى"],
  i_ar:"الكحول يرفع خطر الحماض اللاكتيكي.",
  p_en:"Blood-sugar lowering for type 2 diabetes", b_en:["Improves insulin sensitivity","Low hypoglycemia risk alone"],
  s_en:["Nausea","Diarrhea (usually improves)"], w_en:["Pause before surgery and contrast scans","Caution with kidney disease"],
  i_en:"Alcohol raises lactic acidosis risk."},
 {name:"Amlodipine (أملوديبين)", p_ar:"حاصرات قنوات الكالسيوم لضغط الدم", b_ar:["يخفض الضغط","يحسن جريان الدم التاجي"],
  s_ar:["تورم الكاحل","احمرار الوجه","صداع"], w_ar:["انتظام الجرعة يوميًا بذات الوقت","لا توقفه فجأة"],
  i_ar:"الجريب فروت يرفع تركيزه في الدم.",
  p_en:"Calcium-channel blocker for blood pressure", b_en:["Lowers BP","Improves coronary flow"],
  s_en:["Ankle swelling","Facial flushing","Headache"], w_en:["Take at the same time daily","Do not stop abruptly"],
  i_en:"Grapefruit raises its blood level."},
 {name:"Cetirizine (سيتيريزين)", p_ar:"مضاد هيستامين لأعراض الحساسية", b_ar:["العطاس","الحكة","الدموع"],
  s_ar:["نعاس خفيف"], w_ar:["تجنب القيادة حتى تعرف تأثيره","حذر مع الكلى"],
  i_ar:"الكحول يزيد النعاس.",
  p_en:"Antihistamine for allergy symptoms", b_en:["Sneezing","Itching","Watery eyes"],
  s_en:["Mild drowsiness"], w_en:["Avoid driving until you know its effect","Caution with kidney disease"],
  i_en:"Alcohol increases drowsiness."},
 {name:"Simvastatin (سيمفاستاتين)", p_ar:"خافض للكوليسترول (ستاتين)", b_ar:["يخفض LDL","يقلل مخاطر القلب"],
  s_ar:["آلام عضلية"], w_ar:["أخبر طبيبك فورًا عن ألم عضلات غير مفسّر","تجنب الحمل أثناء استخدامه"],
  i_ar:"الجريب فروت خطر كبير معه — يمنع.",
  p_en:"Cholesterol-lowering statin", b_en:["Lowers LDL","Reduces cardiac risk"],
  s_en:["Muscle aches"], w_en:["Report unexplained muscle pain immediately","Avoid during pregnancy"],
  i_en:"Grapefruit is a major hazard — avoid."},
 {name:"Levothyroxine (ليفوثيروكسين)", p_ar:"هرمون الغدة الدرقية الاصطناعي", b_ar:["يعالج الخمول الدرقي","ينظم الأيض"],
  s_ar:["خفقان عند زيادة الجرعة"], w_ar:["على معدة فارغة صباحًا","افصله 4 ساعات عن الشاي والقهوة والألياف والكالسيوم"],
  i_ar:"الكالسيوم والحديد يثبطان امتصاصه.",
  p_en:"Synthetic thyroid hormone", b_en:["Treats hypothyroidism","Regulates metabolism"],
  s_en:["Palpitations if over-dosed"], w_en:["Empty stomach in the morning","Separate 4h from tea, coffee, fiber, calcium"],
  i_en:"Calcium and iron block its absorption."},
 {name:"Warfarin (وارفارين)", p_ar:"مميّع دم (مضاد فيتامين K)", b_ar:["يمنع الجلطات"],
  s_ar:["سهولة الكدمات","نزيف اللثة"], w_ar:["ثبّت كمية الخضروات الورقية — لا تمنعها ولا تكثر فجأة","إبلاغ أي طبيب أو طبيب أسنان قبل الإجراءات"],
  i_ar:"تفاعلات كثيرة: مضادات الالتهاب، المضادات الحيوية، البنجر، الجريب فروت.",
  p_en:"Blood thinner (vitamin K antagonist)", b_en:["Prevents clots"],
  s_en:["Easy bruising","Gum bleeding"], w_en:["Keep leafy-vegetable intake steady — neither stop nor binge","Tell any dentist or doctor before procedures"],
  i_en:"Many interactions: NSAIDs, antibiotics, beetroot, grapefruit."}
],

/* ===== التحاليل المخبرية (15 محلول) ===== */
LABS: [
 {k:"hb", ar:"الهيموغلوبين", en:"Hemoglobin", unit:"g/dL", low:13, high:17,
  low_ar:"أقل من الطبيعي — قد يشير لفقر دم؛ غالبًا نقص حديد ويحتاج تحديد السبب مع طبيب.",
  low_en:"Below normal — may indicate anemia, often iron deficiency; the cause must be found by a doctor.",
  high_ar:"أعلى من الطبيعي — قد يعكس جفافًا أو حالات أخرى تُقيَّم طبيًا.",
  high_en:"Above normal — may reflect dehydration or other conditions to assess medically."},
 {k:"wbc", ar:"خلايا الدم البيضاء", en:"WBC", unit:"10³/µL", low:4, high:11,
  low_ar:"منخفضة قليلًا — قد تتبع فيروسًا أو أدوية؛ راقب وأعد التحليل.",
  low_en:"Slightly low — may follow a virus or medications; monitor and retest.",
  high_ar:"مرتفعة — غالبًا التهاب أو عدوى حالية؛ تُفسَّر مع الأعراض.",
  high_en:"Elevated — usually current inflammation or infection; interpret with symptoms."},
 {k:"plt", ar:"الصفائح الدموية", en:"Platelets", unit:"10³/µL", low:150, high:410,
  low_ar:"منخفضة — قد تؤثر على التخثر؛ مهم مراجعة الطبيب خاصة مع النزيف أو الكدمات.",
  low_en:"Low — may affect clotting; see a doctor, especially with bleeding or bruising.",
  high_ar:"مرتفعة — قد تتبع التهابًا أو حديدًا؛ تُقيَّم سياقيًا.",
  high_en:"High — may follow inflammation or iron issues; assessed in context."},
 {k:"glu", ar:"سكر الدم صائم", en:"Fasting glucose", unit:"mg/dL", low:70, high:99,
  low_ar:"منخفض — إن كان مع تعرق أو رعشة أو دوخة تناول سكرًا سريعًا واستشر طبيبًا.",
  low_en:"Low — if with sweating, tremor or dizziness take fast sugar and consult a doctor.",
  high_ar:"أعلى من الطبيعي — قد يسبق السكري؛ يؤكَّد بتحليل ثانٍ (HbA1c).",
  high_en:"Above normal — may precede diabetes; confirm with a repeat test (HbA1c)."},
 {k:"hba1c", ar:"السكر التراكمي HbA1c", en:"HbA1c", unit:"%", low:4, high:5.6,
  low_ar:"منخفض — نادر؛ ناقشه مع طبيبك.",
  low_en:"Low — uncommon; discuss with your doctor.",
  high_ar:"مرتفع — 5.7–6.4 مقدمات سكري، و≥6.5 يوافق تشخيص السكري؛ يحتاج تقييمًا طبيًا.",
  high_en:"High — 5.7–6.4 prediabetes, ≥6.5 diabetes range; needs medical evaluation."},
 {k:"cr", ar:"الكرياتينين", en:"Creatinine", unit:"mg/dL", low:0.7, high:1.3,
  low_ar:"منخفض — غالبًا غير مقلق.",
  low_en:"Low — usually not concerning.",
  high_ar:"مرتفع — قد يعكس ضعفًا كلويًا؛ مهم مراجعة طبيب، خاصة مع أدوية الكلى والأملاح.",
  high_en:"High — may reflect reduced kidney function; see a doctor, especially with kidney-affecting meds."},
 {k:"alt", ar:"إنزيم ALT (الكبد)", en:"ALT (liver)", unit:"U/L", low:7, high:56,
  low_ar:"منخفض — غير مقلق عادة.",
  low_en:"Low — usually not concerning.",
  high_ar:"مرتفع — قد يعكس دهونًا كبدية أو التهابًا أو أدوية؛ راجع الطبيب مع بقية التحاليل.",
  high_en:"Elevated — may reflect fatty liver, inflammation or medications; review with a doctor."},
 {k:"tsh", ar:"الهرمون المحفز للدرقية TSH", en:"TSH", unit:"mIU/L", low:0.4, high:4.0,
  low_ar:"منخفض — قد يعني فرط نشاط الدرقية (خفقان، نحافة).",
  low_en:"Low — may mean overactive thyroid (palpitations, weight loss).",
  high_ar:"مرتفع — يوافق خمول الدرقية (تعب، برد، زيادة وزن)؛ علاج بسيط وفعّال بعد تقييم.",
  high_en:"High — matches underactive thyroid (fatigue, cold intolerance); simple effective treatment after evaluation."},
 {k:"na", ar:"الصوديوم", en:"Sodium", unit:"mmol/L", low:136, high:145,
  low_ar:"منخفض — قد يسبب دوخة وضعفًا؛ إن كان شديدًا أو مع تشوش = مراجعة عاجلة.",
  low_en:"Low — may cause dizziness and weakness; severe or with confusion = urgent care.",
  high_ar:"مرتفع — غالبًا جفاف أو ملح زائد؛ زوّد السوائل وراجع طبيبك.",
  high_en:"High — usually dehydration or excess salt; increase fluids and see your doctor."},
 {k:"k", ar:"البوتاسيوم", en:"Potassium", unit:"mmol/L", low:3.5, high:5.1,
  low_ar:"منخفض — قد يسبب ضعفًا وخفقانًا؛ إصلاحه مهم قبل أدوية القلب.",
  low_en:"Low — may cause weakness and palpitations; important to correct, especially with heart meds.",
  high_ar:"مرتفع — قد يكون خطيرًا على القلب؛ عاجل خاصة مع أدوية الكلى أو مدرات البوتاسيوم.",
  high_en:"High — can be dangerous for the heart; urgent especially with kidney disease or potassium-sparing diuretics."},
 {k:"ca", ar:"الكالسيوم", en:"Calcium", unit:"mg/dL", low:8.5, high:10.5,
  low_ar:"منخفض — قد يسبب تقلصات وخدرًا؛ يُقيَّم مع فيتامين D.",
  low_en:"Low — may cause cramps and tingling; assess with vitamin D.",
  high_ar:"مرتفع — قد يعكس جفافًا أو فرط نشاط جارات الدرق؛ يحتاج تقييمًا.",
  high_en:"High — may reflect dehydration or parathyroid overactivity; needs evaluation."},
 {k:"vitd", ar:"فيتامين D", en:"Vitamin D", unit:"ng/mL", low:30, high:100,
  low_ar:"منخفض — شائع جدًا؛ يصحح بالتعرض للشمس والمكملات بإشراف طبي.",
  low_en:"Low — very common; corrected with sunlight and supplements under medical guidance.",
  high_ar:"مرتفع جدًا — غالبًا جرعة مكمل مفرطة؛ راجع جرعتك مع الطبيب.",
  high_en:"Very high — usually excess supplement dosing; review your dose with a doctor."},
 {k:"chol", ar:"الكوليسترول الكلي", en:"Total cholesterol", unit:"mg/dL", low:0, high:200,
  low_ar:"", low_en:"",
  high_ar:"أعلى من المستهدف — يُدار بالغذاء والنشاط أولًا، وقد يحتاج دواء بقرار طبي.",
  high_en:"Above target — managed with diet and activity first; medication is a medical decision."},
 {k:"ldl", ar:"LDL (الكوليسترول الضار)", en:"LDL", unit:"mg/dL", low:0, high:100,
  low_ar:"", low_en:"",
  high_ar:"مرتفع — العامل الأهم لخطر القلب؛ ناقش خياراتك مع طبيبك.",
  high_en:"High — the key driver of cardiac risk; discuss options with your doctor."},
 {k:"uric", ar:"حمض اليوريك", en:"Uric acid", unit:"mg/dL", low:0, high:7.0,
  low_ar:"", low_en:"",
  high_ar:"مرتفع — قد يهيئ للنقرس وحصوات؛ قلّل اللحوم والمحار والبيرة وراجع طبيبك.",
  high_en:"High — may predispose to gout and stones; reduce meat, shellfish and beer, see your doctor."}
],

/* ===== محرك المقابلة: مسارات أعراض + علامات خطر حمراء ===== */
FLOWS: [
 {k:"chest", icon:"🫀", ar:"ألم في الصدر", en:"Chest pain",
  spec_ar:"طبيب قلب / طوارئ", spec_en:"Cardiologist / ER",
  qs:[
   {ar:"هل يزداد الألم مع المجهود البدني؟", en:"Does the pain worsen with physical exertion?", red:"emergency"},
   {ar:"هل تشعر بضيق في التنفس؟", en:"Do you have shortness of breath?", red:"emergency"},
   {ar:"هل يمتد الألم إلى الذراع أو الفك أو الظهر؟", en:"Does the pain radiate to the arm, jaw or back?", red:"emergency"},
   {ar:"هل يصاحبه تعرق غزير أو غثيان أو دوخة شديدة؟", en:"Is it accompanied by heavy sweating, nausea or severe dizziness?", red:"emergency"}],
  base:{ar:"ألم صدر عضلي/هضمي محتمل", en:"Likely musculoskeletal or digestive chest pain"},
  base_t:{ar:"بدون علامات إنذار، يكون الألم غالبًا من جدار الصدر أو الارتجاع. راقب الأعراض، وتجنب الوجبات الثقيلة قبل النوم.", en:"Without warning signs, the pain is usually chest-wall or reflux related. Monitor symptoms and avoid heavy meals before bed."},
  diff:[{ar:"التهاب غضروف الأضلاع", en:"Costochondritis", w:1},{ar:"ارتجاع مريئي", en:"GERD", w:1},{ar:"قلق وتوتر", en:"Anxiety", w:0.5}],
  food:"reflux"},
 {k:"consti", icon:"🌀", ar:"إمساك", en:"Constipation",
  spec_ar:"طبيب باطنية", spec_en:"Internist",
  qs:[
   {ar:"هل استمر الإمساك أكثر من أسبوعين؟", en:"Has constipation lasted over 2 weeks?", red:null},
   {ar:"هل لاحظت دمًا في البراز؟", en:"Have you noticed blood in the stool?", red:"urgent"},
   {ar:"هل يوجد ألم بطن شديد أو انتفاخ أو قيء؟", en:"Any severe abdominal pain, bloating or vomiting?", red:"urgent"},
   {ar:"هل فقدت وزنًا دون محاولة؟", en:"Any unintentional weight loss?", red:"urgent"}],
  base:{ar:"إمساك وظيفي بسيط", en:"Simple functional constipation"},
  base_t:{ar:"إمساك مؤقت شائع يتحسن بالألياف والسوائل والنشاط خلال أيام.", en:"Common temporary constipation improving with fiber, fluids and activity within days."},
  diff:[{ar:"قصور الغدة الدرقية", en:"Hypothyroidism", w:0.5},{ar:"تأثير أدوية (حديد، ألمبياد)", en:"Medication effect (iron, opioids)", w:0.5}],
  food:"constipation"},
 {k:"reflux", icon:"🔥", ar:"حموضة وحرقان", en:"Heartburn / reflux",
  spec_ar:"طبيب جهاز هضمي", spec_en:"Gastroenterologist",
  qs:[
   {ar:"هل يصاحبها صعوبة أو ألم عند البلع؟", en:"Any difficulty or pain when swallowing?", red:"urgent"},
   {ar:"هل يوجد قيء دم أو براز أسود؟", en:"Any vomiting blood or black stool?", red:"urgent"},
   {ar:"هل تستيقظ بألم صدري ليلًا بشكل متكرر؟", en:"Frequent nighttime chest pain waking you up?", red:"urgent"},
   {ar:"هل استمرت الأعراض أكثر من 4 أسابيع رغم المضادات البسيطة؟", en:"Symptoms over 4 weeks despite simple antacids?", red:null}],
  base:{ar:"ارتجاع مريئي (GERD)", en:"Gastroesophageal reflux (GERD)"},
  base_t:{ar:"حرقان بعد الوجبات دون علامات تنبيه يُدار بالغذاء ونمط الحياة أولًا.", en:"Post-meal burning without warning signs is managed with diet and lifestyle first."},
  diff:[{ar:"قرحة المعدة", en:"Gastric ulcer", w:0.5},{ar:"حصوات المرارة", en:"Gallstones", w:0.5}],
  food:"reflux"},
 {k:"headache", icon:"🤕", ar:"صداع", en:"Headache",
  spec_ar:"طبيب أعصاب", spec_en:"Neurologist",
  qs:[
   {ar:"هل هو أشد صداع في حياتك فجأة وخلال ثوانٍ؟", en:"Is it the worst sudden headache of your life, within seconds?", red:"emergency"},
   {ar:"هل يصاحبه ضعف أو خدر في طرف أو صعوبة كلام؟", en:"Any limb weakness, numbness or speech difficulty?", red:"emergency"},
   {ar:"هل معه حمى ورقبة متيبسة أو طفح لا يختفي بالضغط؟", en:"Fever with stiff neck or non-blanching rash?", red:"emergency"},
   {ar:"هل يزداد مع الانحناء أو السعال؟", en:"Does it worsen with bending or coughing?", red:"urgent"},
   {ar:"هل استمر أكثر من 3 أيام متواصلة؟", en:"Has it lasted more than 3 continuous days?", red:null}],
  base:{ar:"صداع توتري أو نصفي محتمل", en:"Likely tension-type or migraine headache"},
  base_t:{ar:"الصداع النمطي المتكرر غالبًا توتري أو نصفي — يساعده النوم المنتظم والترطيب وتقليل الكافيين.", en:"Typical recurrent headaches are usually tension or migraine — helped by regular sleep, hydration and less caffeine."},
  diff:[{ar:"الصداع النصفي", en:"Migraine", w:1},{ar:"صداع التوتر", en:"Tension headache", w:1},{ar:"تهيج الجيوب الأنفية", en:"Sinus irritation", w:0.5}],
  food:null},
 {k:"diarrhea", icon:"💧", ar:"إسهال", en:"Diarrhea",
  spec_ar:"طبيب باطنية", spec_en:"Internist",
  qs:[
   {ar:"هل توجد دم أو مخاط في البراز؟", en:"Any blood or mucus in stool?", red:"urgent"},
   {ar:"هل لاحظت علامات جفاف (عطش شديد، بول قليل داكن، دوخة)؟", en:"Any dehydration signs (severe thirst, scant dark urine, dizziness)?", red:"urgent"},
   {ar:"هل معه حمى فوق 38.5؟", en:"Fever above 38.5°C?", red:"urgent"},
   {ar:"هل استمر أكثر من 3 أيام؟", en:"Has it lasted more than 3 days?", red:null}],
  base:{ar:"إسهال فيروسي/غذائي حاد غالبًا", en:"Likely acute viral/food-related diarrhea"},
  base_t:{ar:"الإسهال الحاد غير الدموي يتحسن خلال 2–3 أيام مع السوائل ومحلول الأملاح والرزاق الخفيف.", en:"Acute non-bloody diarrhea improves within 2–3 days with fluids, ORS and light bland food."},
  diff:[{ar:"تعفن غذائي", en:"Food poisoning", w:1},{ar:"عدوى فيروسية", en:"Viral infection", w:1},{ar:"عدم تحمل الطعام", en:"Food intolerance", w:0.5}],
  food:"diarrhea"},
 {k:"thirst", icon:"🥤", ar:"عطش شديد وتبول متكرر", en:"Excessive thirst & urination",
  spec_ar:"طبيب غدد صم/باطنية", spec_en:"Endocrinologist / Internist",
  qs:[
   {ar:"هل فقدت وزنًا بسرعة رغم الأكل الطبيعي؟", en:"Rapid weight loss despite normal eating?", red:"urgent"},
   {ar:"هل تشعر بغثيان أو قيء أو رائحة فم كريهة؟", en:"Nausea, vomiting or fruity breath odor?", red:"emergency"},
   {ar:"هل معك خمول شديد أو تشوش؟", en:"Severe drowsiness or confusion?", red:"emergency"},
   {ar:"هل تبولت أكثر من 8 مرات يوميًا لأكثر من أسبوع؟", en:"Urinating over 8 times daily for more than a week?", red:null}],
  base:{ar:"قد تكون أعراضًا مبكرة لارتفاع السكر", en:"May be early symptoms of high blood sugar"},
  base_t:{ar:"العطش والتبول المتكرر المستمران يستوجبان فحص سكر بسيط. مبكرًا تكون السيطرة أسهل بكثير.", en:"Persistent thirst and frequent urination deserve a simple sugar test. Early control is far easier."},
  diff:[{ar:"مقدمات السكري/السكري", en:"Prediabetes / diabetes", w:1},{ar:"جفاف بسيط", en:"Mild dehydration", w:0.5},{ar:"تهيّج المثانة", en:"Bladder irritation", w:0.5}],
  food:"diabetes"},
 {k:"cough", icon:"🫁", ar:"كحة مزمنة", en:"Chronic cough",
  spec_ar:"طبيب صدرية", spec_en:"Pulmonologist",
  qs:[
   {ar:"هل معها دم في البلغم؟", en:"Any blood in sputum?", red:"urgent"},
   {ar:"هل معها حمى وعرق ليلي وفقدان وزن؟", en:"Fever, night sweats and weight loss?", red:"urgent"},
   {ar:"هل يوجد ضيق تنفس أو صفير عند الزفير؟", en:"Shortness of breath or wheezing on exhale?", red:null},
   {ar:"هل استمرت أكثر من 8 أسابيع؟", en:"Has it lasted over 8 weeks?", red:null}],
  base:{ar:"كحة ما بعد نزلة برد أو رجوع حمضي", en:"Post-viral or acid-reflux cough"},
  base_t:{ar:"الكحة المستمرة بعد نزلة برد شائعة وتزول خلال أسابيع. تجنب التدخين والمهيجات.", en:"A lingering cough after a cold is common and fades within weeks. Avoid smoking and irritants."},
  diff:[{ar:"ربو/التهاب قصبات", en:"Asthma / bronchitis", w:1},{ar:"ارتجاع يسبب كحة", en:"Reflux-related cough", w:0.5},{ar:"حساسية", en:"Allergy", w:0.5}],
  food:null}
],

/* ===== تعارضات دوائية-غذائية يفحصها التطبيق ===== */
INTERACTIONS: [
 {med:"amlodipine", food:"الجريب فروت", food_en:"Grapefruit", sev:"high",
  ar:"الجريب فروت يرفع تركيز أملوديبين وقد يخفض الضغط بشكل مفرط.",
  en:"Grapefruit raises amlodipine levels and may drop blood pressure excessively."},
 {med:"amlodipine", food:"grapefruit", food_en:"Grapefruit", sev:"high",
  ar:"الجريب فروت يرفع تركيز أملوديبين وقد يخفض الضغط بشكل مفرط.",
  en:"Grapefruit raises amlodipine levels and may drop blood pressure excessively."},
 {med:"simvastatin", food:"الجريب فروت", food_en:"Grapefruit", sev:"high",
  ar:"خطورة عالية: الجريب فروت مع السيمفاستاتين يرفع خطر تدمير العضلات.",
  en:"High risk: grapefruit with simvastatin raises muscle-breakdown risk."},
 {med:"warfarin", food:"السبانخ والخضروات الورقية بكميات متغيرة", food_en:"Variable leafy greens", sev:"medium",
  ar:"فيتامين K يعاكس عمل الوارفارين: ثبّت كميتك الأسبوعية ولا تتأرجح بين المنع والإفراط.",
  en:"Vitamin K opposes warfarin: keep weekly intake steady, do not swing between avoiding and binging."},
 {med:"warfarin", food:"grapefruit", food_en:"Grapefruit", sev:"medium",
  ar:"الجريب فروت قد يرفع تأثير الوارفارين وزيادة النزيف.",
  en:"Grapefruit may intensify warfarin and bleeding risk."},
 {med:"levothyroxine", food:"الشاي والقهوة والألياف والكالسيوم", food_en:"Tea, coffee, fiber, calcium", sev:"medium",
  ar:"تثبط امتصاص الهرمون: افصل 4 ساعات بين الحبوب وأي منها.",
  en:"They block hormone absorption: separate by 4 hours."},
 {med:"ibuprofen", food:"الكحول", food_en:"Alcohol", sev:"high",
  ar:"الجمع بينهما يرفع خطر النزيف المعدي بشكل كبير.",
  en:"Combining them markedly raises stomach-bleeding risk."},
 {med:"metformin", food:"الكحول", food_en:"Alcohol", sev:"high",
  ar:"الكحول مع الميتفورمين يرفع خطر الحماض اللاكتيكي النادر لكن الخطير.",
  en:"Alcohol with metformin raises risk of rare but dangerous lactic acidosis."},
 {med:"omeprazole", food:"", food_en:"", sev:"low",
  ar:"استخدام طويل قد يخفض المغنيسيوم وB12 — راجع طبيبك سنويًا.",
  en:"Long-term use may lower magnesium and B12 — annual review advised."}
],

/* اختيارات الأدوية في الملف الشخصي (مطابقة للمفاتيح أعلاه) */
MED_OPTIONS: [
 {v:"amlodipine", ar:"أملوديبين (ضغط)", en:"Amlodipine (BP)"},
 {v:"simvastatin", ar:"سيمفاستاتين (كوليسترول)", en:"Simvastatin (cholesterol)"},
 {v:"warfarin", ar:"وارفارين (مميع)", en:"Warfarin (blood thinner)"},
 {v:"levothyroxine", ar:"ليفوثيروكسين (درقية)", en:"Levothyroxine (thyroid)"},
 {v:"metformin", ar:"ميتفورمين (سكري)", en:"Metformin (diabetes)"},
 {v:"ibuprofen", ar:"إيبوبروفين (مسكن)", en:"Ibuprofen (painkiller)"},
 {v:"omeprazole", ar:"أوميبرازول (حموضة)", en:"Omeprazole (acid)"}
],

/* الأمراض المزمنة في الملف الشخصي → تخصيص النصائح الغذائية */
CONDITION_OPTIONS: [
 {v:"ckd", ar:"أمراض الكلى", en:"Kidney disease", blocks:["potassium-rich","high-potassium"]},
 {v:"diabetes", ar:"السكري", en:"Diabetes", food:"diabetes"},
 {v:"hypertension", ar:"ضغط الدم", en:"Hypertension", food:"hypertension"},
 {v:"gout", ar:"النقرس", en:"Gout", food:"gout"},
 {v:"anemia", ar:"فقر الدم", en:"Anemia", food:"anemia"}
]
};